name: Cookiecutter

on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  PIP_NO_OPTION: on
  PIP_NO_CLEAN: on
  PIP_PREFER_BINARY: on

jobs:
  cruft:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Cache requirements
        uses: actions/cache@v4
        env:
          cache-name: cache-requirements
        with:
          path: ~/.cache/pip
          {% raw %}key: ${{ env.cache-name }}-${{ hashFiles('requirements.txt') }}{% endraw %}
          restore-keys: |
            {% raw %}${{ env.cache-name }}-{% endraw %}

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install requirements
        run: make setup

      - name: Check template
        run: cruft check
