name: Release

run-name: bump {% raw %}${{ inputs.version }} version by @${{ github.actor }}{% endraw %}

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: 'part of the project version to update'
        options:
        - major
        - minor
        - patch
        required: true

env:
  PIP_DISABLE_PIP_VERSION_CHECK: on
  PIP_NO_CLEAN: on
  PIP_NO_INPUT: on
  PIP_PREFER_BINARY: on
  PY_COLORS: "1"
  MEX_BOT_EMAIL: mex@rki.de
  MEX_BOT_USER: RKIMetadataExchange

concurrency:
  group: {% raw %}${{ github.workflow }}-${{ github.ref }}{% endraw %}
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    outputs:
      tag: {% raw %}${{ steps.release.outputs.tag }}{% endraw %}

    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Cache requirements
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        env:
          cache-name: cache-requirements
        with:
          path: ~/.cache/pip
          {% raw %}key: ${{ env.cache-name }}-${{ hashFiles('requirements.txt') }}{% endraw %}
          restore-keys: |
            {% raw %}${{ env.cache-name }}-{% endraw %}

      - name: Setup python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.14

      - name: Install requirements
        run: make setup

      - name: Configure git
        env:
          {% raw %}SIGNING_KEY: ${{ secrets.MEX_SIGNING_KEY }}{% endraw %}
          {% raw %}SIGNING_PUB: ${{ vars.MEX_SIGNING_PUB }}{% endraw %}
        run: |
          {% raw -%}
          eval "$(ssh-agent -s)"
          mex setup-commit-signing
          {%- endraw %}

      - name: Release new version
        id: release
        env:
          {% raw %}GH_TOKEN: ${{ secrets.MEX_CONTENT_WRITE_TOKEN }}{% endraw %}
        run: |
          {% raw -%}
          git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          mex release ${{ inputs.version }}
          echo "tag=$(git describe --abbrev=0 --tags)" >> "$GITHUB_OUTPUT"
          {%- endraw %}

  containerize:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: release
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1
          {% raw %}ref: ${{ needs.release.outputs.tag }}{% endraw %}
          persist-credentials: false

      - name: Login to container registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ghcr.io
          username: {% raw %}${{github.actor}}{% endraw %}
          password: {% raw %}${{secrets.GITHUB_TOKEN}}{% endraw %}

      - name: Build, tag and push docker image
        env:
          {% raw %}IMAGE: ghcr.io/${{ github.repository }}{% endraw %}
          {% raw %}TAG: ${{ needs.release.outputs.tag }}{% endraw %}
        run: |
          {% raw -%}
          docker build . \
          --tag ${IMAGE}:latest \
          --tag ${IMAGE}:${{ github.sha }} \
          --tag ${IMAGE}:${TAG}
          docker push --all-tags ${IMAGE}
          {%- endraw %}

  distribute:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: release
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1
          {% raw %}ref: ${{ needs.release.outputs.tag }}{% endraw %}
          persist-credentials: false

      - name: Cache requirements
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        env:
          cache-name: cache-requirements
        with:
          path: ~/.cache/pip
          {% raw %}key: ${{ env.cache-name }}-${{ hashFiles('requirements.txt') }}{% endraw %}
          restore-keys: |
            {% raw %}${{ env.cache-name }}-{% endraw %}

      - name: Setup python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.14

      - name: Install requirements
        run: make setup

      - name: Build wheel and sdist distros and create a github release
        env:
          {% raw %}GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}{% endraw %}
        run: |
          {% raw -%}
          uv build --out-dir dist
          gh release create ${{ needs.release.outputs.tag }} \
          --generate-notes --latest --verify-tag dist/*
          {%- endraw %}
