name: Release

run-name: bump {% raw %}${{ inputs.version }} version by @${{ github.actor }}{% endraw %}

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: 'part of the project version to update'
        options:
        - major
        - minor
        - patch
        required: true

env:
  PIP_DISABLE_PIP_VERSION_CHECK: on
  PIP_NO_CLEAN: on
  PIP_NO_INPUT: on
  PIP_PREFER_BINARY: on
  PY_COLORS: "1"

permissions:
  contents: write
  packages: write

concurrency:
  group: {% raw %}${{ github.workflow }}-${{ github.ref }}{% endraw %}
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      tag: {% raw %}${{ steps.release.outputs.tag }}{% endraw %}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
          token: {% raw %}${{ secrets.WORKFLOW_TOKEN }}{% endraw %}

      - name: Cache requirements
        uses: actions/cache@v4
        env:
          cache-name: cache-requirements
        with:
          path: ~/.cache/pip
          {% raw %}key: ${{ env.cache-name }}-${{ hashFiles('requirements.txt') }}{% endraw %}
          restore-keys: |
            {% raw %}${{ env.cache-name }}-{% endraw %}

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install requirements
        run: make setup

      - name: Configure git
        env:
          {% raw %}MEX_BOT_EMAIL: ${{ vars.MEX_BOT_EMAIL }}{% endraw %}
          {% raw %}MEX_BOT_USER: ${{ vars.MEX_BOT_USER }}{% endraw %}
          {% raw %}SIGNING_KEY: ${{ secrets.SIGNING_KEY }}{% endraw %}
          {% raw %}SIGNING_PUB: ${{ secrets.SIGNING_PUB }}{% endraw %}
        run: |
          {% raw -%}
          eval "$(ssh-agent -s)"
          pdm setup-commit-signing
          {%- endraw %}

      - name: Release new version
        id: release
        run: |
          pdm release {% raw %}${{ inputs.version }}{% endraw %}
          echo "tag=$(git describe --abbrev=0 --tags)" >> "$GITHUB_OUTPUT"

  containerize:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: release
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
          {% raw %}ref: ${{ needs.release.outputs.tag }}{% endraw %}
          persist-credentials: false

      - name: Cache requirements
        uses: actions/cache@v4
        env:
          cache-name: cache-requirements
        with:
          path: ~/.cache/pip
          key: {% raw %}${{ env.cache-name }}-${{ hashFiles('requirements.txt') }}{% endraw %}
          restore-keys: |
            {% raw %}${{ env.cache-name }}-{% endraw %}

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install requirements
        run: make setup

      - name: Generate locked requirements.txt
        run: |
          pdm export --self --output locked-requirements.txt --no-hashes --without dev

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: {% raw %}${{github.actor}}{% endraw %}
          password: {% raw %}${{secrets.GITHUB_TOKEN}}{% endraw %}

      - name: Build, tag and push docker image
        run: |
          docker build . \
          --tag ghcr.io/robert-koch-institut/mex-{{ cookiecutter.project_name }}:latest \
          --tag ghcr.io/robert-koch-institut/mex-{{ cookiecutter.project_name }}:{% raw %}${{ github.sha }}{% endraw %} \
          --tag ghcr.io/robert-koch-institut/mex-{{ cookiecutter.project_name }}:{% raw %}${{ needs.release.outputs.tag }}{% endraw %}
          docker push --all-tags ghcr.io/robert-koch-institut/mex-{{ cookiecutter.project_name }}

  distribute:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: release
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
          {% raw %}ref: ${{ needs.release.outputs.tag }}{% endraw %}
          persist-credentials: false

      - name: Cache requirements
        uses: actions/cache@v4
        env:
          cache-name: cache-requirements
        with:
          path: ~/.cache/pip
          {% raw %}key: ${{ env.cache-name }}-${{ hashFiles('requirements.txt') }}{% endraw %}
          restore-keys: |
            {% raw %}${{ env.cache-name }}-{% endraw %}

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install requirements
        run: make setup

      - name: Build wheel and sdist distros and create a github release
        env:
          {% raw %}GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}{% endraw %}
        run: |
          {% raw -%}
          gh release create ${{ needs.release.outputs.tag }} --generate-notes --latest --verify-tag
          pdm build --dest dist
          for filename in dist/*; do
            gh release upload ${{ needs.release.outputs.tag }} ${filename};
          done
          {%- endraw %}
