name: CVE Scan

on:
  push:
    branches: ["main"]
    tags: ["**"]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  schedule:
    - cron: "14 3 * * 1-5"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run trivy
        uses: aquasecurity/trivy-action@master
        with:
          format: 'sarif'
          list-all-pkgs: 'true'
          output: 'trivy-results.sarif'
          scan-ref: '.'
          scan-type: 'fs'
          severity: 'MEDIUM,HIGH,CRITICAL'

      - name: Publish results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
